name: Build

on:
  workflow_call:
    inputs:
      channel:
        type: string
        default: ''
      version:
        type: string
        default: ''
      notify:
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      channel:
        type: choice
        description: Select the channel
        options:
          - preview
          - staging
      channel-text:
        description: Or specify another channel
        required: false
      notify:
        type: boolean
        description: Notify to Slack
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - env:
          ABC: ${{ inputs.channel-text || inputs.channel || 'preview' }}
          XXX: ${{ inputs.notify && 'true' || 'false' }}
        run: |
          echo $ABC $XXX
       
