name: Bump Deps

on:
  workflow_dispatch:

jobs:
  bump-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: holepunchto/actions/.github/steps/bump-deps@08998c7666a9277d5e2aea473871b761086ccf04
        with:
          use-checkout: true
          use-git-config: true
          use-create-pr: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
