name: Bump Deps

on:
  workflow_dispatch:

jobs:
  bump-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: holepunchto/actions/.github/steps/bump-deps@2bd56cbb3cf9aee8e6891fa423a9f090dbdb9e6a
        with:
          use-checkout: true
          use-git-config: true
          use-create-pr: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: holepunchto/actions/.github/steps/bump-versions@2bd56cbb3cf9aee8e6891fa423a9f090dbdb9e6a
        with:
          use-checkout: true
          use-git-config: true
          use-create-pr: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          version: minor
