name: Bump Deps

on:
  workflow_dispatch:

jobs:
  bump-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: maidh91/test-gha-secret/.github/steps/bump-deps@main
        with:
          use-checkout: true
          use-git-config: true
          use-create-pr: false
